In [2]:
import pandas as pd

In [3]:
data=pd.read_csv(r"C:\Users\kumar\Downloads\aisles.csv")

In [7]:
data.head(10)

   aisle_id                       aisle
0         1       prepared soups salads
1         2           specialty cheeses
2         3         energy granola bars
3         4               instant foods
4         5  marinades meat preparation
5         6                       other
6         7               packaged meat
7         8             bakery desserts
8         9                 pasta sauce
9        10            kitchen supplies

In [11]:
list=[]
for i in range(0,data.shape[0]):
    list.append(data["aisle"][i])

In [13]:
import collections

In [15]:
p=collections.Counter(list)

In [18]:
d={"product":p.keys(),"count":p.values()}

In [19]:
seema=pd.DataFrame(d)

In [21]:
seema.sort_values(by=["product"],ascending=False)

                           product  count
119                         yogurt      1
61                     white wines      1
114  water seltzer sparkling water      1
46            vitamins supplements      1
59               trash bags liners      1
..                             ...    ...
91               baby food formula      1
101            baby bath body care      1
81                baby accessories      1
65                     asian foods      1
100         air fresheners candles      1

[134 rows x 2 columns]

In [22]:
df=pd.read_csv(r"C:\Users\kumar\Downloads\Supermart Grocery Sales - Retail Analytics Dataset.csv")

In [23]:
df.head()

,Order ID,Customer Name,Category,Sub Category,City,Order Date,Region,Sales,Discount,Profit,State
0,OD1,Harish,Oil & Masala,Masalas,Vellore,11-08-2017,North,1254,0.12,401.28,Tamil Nadu
1,OD2,Sudha,Beverages,Health Drinks,Krishnagiri,11-08-2017,South,749,0.18,149.80,Tamil Nadu
2,OD3,Hussain,Food Grains,Atta & Flour,Perambalur,06-12-2017,West,2360,0.21,165.20,Tamil Nadu
3,OD4,Jackson,Fruits & Veggies,Fresh Vegetables,Dharmapuri,10-11-2016,South,896,0.25,89.60,Tamil Nadu
4,OD5,Ridhesh,Food Grains,Organic Staples,Ooty,10-11-2016,South,2355,0.26,918.45,Tamil Nadu

In [26]:
x=df[["Category","Sub Category"]]

In [37]:
x.shape

(9994, 2)

In [30]:
x.head()

           Category      Sub Category
0      Oil & Masala           Masalas
1         Beverages     Health Drinks
2       Food Grains      Atta & Flour
3  Fruits & Veggies  Fresh Vegetables
4       Food Grains   Organic Staples

In [39]:
s=[]
for i in range(0,x.shape[0]):
    d=[]
    for j in x.columns:
         d.append(x[j][i])
    s.append(d)

In [42]:
list=[]
for i in s:
    for j in i:
        list.append(j)

In [46]:
f=collections.Counter(list)

In [54]:
z={"product":f.keys(),"frequently buyes":f.values()}

In [55]:
ku=pd.DataFrame(z)

In [56]:
ku.sort_values(by=["frequently buyes"],ascending=False)

               product  frequently buyes
13              Snacks              1514
15   Eggs, Meat & Fish              1490
6     Fruits & Veggies              1418
10              Bakery              1413
2            Beverages              1400
4          Food Grains              1398
0         Oil & Masala              1361
3        Health Drinks               719
21         Soft Drinks               681
17             Cookies               520
29       Breads & Buns               502
14          Chocolates               499
24             Noodles               495
1              Masalas               463
11            Biscuits               459
12               Cakes               452
19   Edible Oil & Ghee               451
27              Spices               447
20              Mutton               394
16                Eggs               379
8      Organic Staples               372
9         Fresh Fruits               369
26                Fish               369
7     Fresh Vegetables               354
5         Atta & Flour               353
18             Chicken               348
25      Organic Fruits               348
23  Organic Vegetables               347
22       Dals & Pulses               343
28                Rice               330

In [62]:
from mlxtend.preprocessing.transactionencoder import TransactionEncoder

In [63]:
tr=TransactionEncoder()

In [64]:
tr.fit(s)

TransactionEncoder()

In [66]:
 zz=pd.DataFrame(tr.transform(s),columns=tr.columns_)

In [67]:
zz

,Atta & Flour,Bakery,Beverages,Biscuits,Breads & Buns,Cakes,Chicken,Chocolates,Cookies,Dals & Pulses,...,Mutton,Noodles,Oil & Masala,Organic Fruits,Organic Staples,Organic Vegetables,Rice,Snacks,Soft Drinks,Spices
0,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
1,False,False,True,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9990,False,True,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9991,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
9992,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,True
9993,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [68]:
from mlxtend.frequent_patterns import apriori

In [73]:
apriori(zz,min_support=0.03,use_colnames=True,max_len=3).sort_values(by=["support"],ascending=False)

     support                                itemsets
27  0.151491                                (Snacks)
12  0.149089                     (Eggs, Meat & Fish)
17  0.141885                      (Fruits & Veggies)
1   0.141385                                (Bakery)
2   0.140084                             (Beverages)
14  0.139884                           (Food Grains)
22  0.136182                          (Oil & Masala)
18  0.071943                         (Health Drinks)
34  0.071943              (Beverages, Health Drinks)
28  0.068141                           (Soft Drinks)
35  0.068141                (Beverages, Soft Drinks)
38  0.052031                       (Snacks, Cookies)
8   0.052031                               (Cookies)
4   0.050230                         (Breads & Buns)
32  0.050230                 (Bakery, Breads & Buns)
37  0.049930                    (Snacks, Chocolates)
7   0.049930                            (Chocolates)
51  0.049530                       (Snacks, Noodles)
21  0.049530                               (Noodles)
19  0.046328                               (Masalas)
50  0.046328                 (Masalas, Oil & Masala)
3   0.045928                              (Biscuits)
31  0.045928                      (Bakery, Biscuits)
33  0.045227                         (Bakery, Cakes)
5   0.045227                                 (Cakes)
10  0.045127                     (Edible Oil & Ghee)
40  0.045127       (Edible Oil & Ghee, Oil & Masala)
52  0.044727                  (Spices, Oil & Masala)
29  0.044727                                (Spices)
43  0.039424             (Eggs, Meat & Fish, Mutton)
20  0.039424                                (Mutton)
11  0.037923                                  (Eggs)
41  0.037923               (Eggs, Meat & Fish, Eggs)
44  0.037222          (Food Grains, Organic Staples)
24  0.037222                       (Organic Staples)
13  0.036922                                  (Fish)
15  0.036922                          (Fresh Fruits)
46  0.036922        (Fruits & Veggies, Fresh Fruits)
42  0.036922               (Eggs, Meat & Fish, Fish)
47  0.035421    (Fresh Vegetables, Fruits & Veggies)
16  0.035421                      (Fresh Vegetables)
0   0.035321                          (Atta & Flour)
30  0.035321             (Food Grains, Atta & Flour)
48  0.034821      (Organic Fruits, Fruits & Veggies)
6   0.034821                               (Chicken)
36  0.034821            (Chicken, Eggs, Meat & Fish)
23  0.034821                        (Organic Fruits)
49  0.034721  (Organic Vegetables, Fruits & Veggies)
25  0.034721                    (Organic Vegetables)
9   0.034321                         (Dals & Pulses)
39  0.034321            (Food Grains, Dals & Pulses)
26  0.033020                                  (Rice)
45  0.033020                     (Rice, Food Grains)

In [74]:
from mlxtend.frequent_patterns import fpgrowth

In [76]:
fpgrowth(zz,min_support=0.03,max_len=3,use_colnames=True).sort_values(by=["support"],ascending=False)

     support                                itemsets
13  0.151491                                (Snacks)
15  0.149089                     (Eggs, Meat & Fish)
6   0.141885                      (Fruits & Veggies)
10  0.141385                                (Bakery)
2   0.140084                             (Beverages)
4   0.139884                           (Food Grains)
0   0.136182                          (Oil & Masala)
3   0.071943                         (Health Drinks)
31  0.071943              (Beverages, Health Drinks)
21  0.068141                           (Soft Drinks)
44  0.068141                (Beverages, Soft Drinks)
40  0.052031                       (Snacks, Cookies)
17  0.052031                               (Cookies)
52  0.050230                 (Bakery, Breads & Buns)
29  0.050230                         (Breads & Buns)
14  0.049930                            (Chocolates)
38  0.049930                    (Snacks, Chocolates)
24  0.049530                               (Noodles)
47  0.049530                       (Snacks, Noodles)
30  0.046328                 (Masalas, Oil & Masala)
1   0.046328                               (Masalas)
36  0.045928                      (Bakery, Biscuits)
11  0.045928                              (Biscuits)
12  0.045227                                 (Cakes)
37  0.045227                         (Bakery, Cakes)
42  0.045127       (Edible Oil & Ghee, Oil & Masala)
19  0.045127                     (Edible Oil & Ghee)
27  0.044727                                (Spices)
50  0.044727                  (Spices, Oil & Masala)
20  0.039424                                (Mutton)
43  0.039424             (Eggs, Meat & Fish, Mutton)
39  0.037923               (Eggs, Meat & Fish, Eggs)
16  0.037923                                  (Eggs)
8   0.037222                       (Organic Staples)
34  0.037222          (Food Grains, Organic Staples)
49  0.036922               (Eggs, Meat & Fish, Fish)
9   0.036922                          (Fresh Fruits)
35  0.036922        (Fruits & Veggies, Fresh Fruits)
26  0.036922                                  (Fish)
7   0.035421                      (Fresh Vegetables)
33  0.035421    (Fresh Vegetables, Fruits & Veggies)
32  0.035321             (Food Grains, Atta & Flour)
5   0.035321                          (Atta & Flour)
18  0.034821                               (Chicken)
25  0.034821                        (Organic Fruits)
48  0.034821      (Organic Fruits, Fruits & Veggies)
41  0.034821            (Chicken, Eggs, Meat & Fish)
23  0.034721                    (Organic Vegetables)
46  0.034721  (Organic Vegetables, Fruits & Veggies)
45  0.034321            (Food Grains, Dals & Pulses)
22  0.034321                         (Dals & Pulses)
28  0.033020                                  (Rice)
51  0.033020                     (Rice, Food Grains)