In [1]:
import pandas as pd
import numpy as np

In [3]:
data=pd.read_csv(r"C:\Users\kumar\Downloads\Grocery Products Purchase.csv")

In [4]:
df=data.copy()

In [14]:
df

,Product 1,Product 2,Product 3,Product 4,Product 5,Product 6,Product 7,Product 8,Product 9,Product 10,...,Product 23,Product 24,Product 25,Product 26,Product 27,Product 28,Product 29,Product 30,Product 31,Product 32
0,citrus fruit,semi-finished bread,margarine,ready soups,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,tropical fruit,yogurt,coffee,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,whole milk,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,pip fruit,yogurt,cream cheese,meat spreads,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,other vegetables,whole milk,condensed milk,long life bakery product,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9830,sausage,chicken,beef,hamburger meat,citrus fruit,grapes,root vegetables,whole milk,butter,whipped/sour cream,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9831,cooking chocolate,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9832,chicken,citrus fruit,other vegetables,butter,yogurt,frozen dessert,domestic eggs,rolls/buns,rum,cling film/bags,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9833,semi-finished bread,bottled water,soda,bottled beer,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9834,chicken,tropical fruit,other vegetables,vinegar,shopping bags,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
type(df.loc[1,"Product 5"])

float

In [46]:
list1=[]

In [25]:
colums=df.columns

In [26]:
colums

Index(['Product 1', 'Product 2', 'Product 3', 'Product 4', 'Product 5',
       'Product 6', 'Product 7', 'Product 8', 'Product 9', 'Product 10',
       'Product 11', 'Product 12', 'Product 13', 'Product 14', 'Product 15',
       'Product 16', 'Product 17', 'Product 18', 'Product 19', 'Product 20',
       'Product 21', 'Product 22', 'Product 23', 'Product 24', 'Product 25',
       'Product 26', 'Product 27', 'Product 28', 'Product 29', 'Product 30',
       'Product 31', 'Product 32'],
      dtype='object')

In [45]:
type(df["Product 5"][0])

float

In [47]:
for i in range(0,df.shape[0]):
    list2=[]
    for colum in colums:
        if(type(df[colum][i])==str):
            list2.append(df[colum][i])
    list1.append(list2)

In [49]:
market=[]
for i in list1:
    for j in i:
        market.append(j)

In [53]:
#market

In [54]:
import collections

In [55]:
p=collections.Counter(market)

In [57]:
se={"product":p.keys(),"values":p.values()}
d=pd.DataFrame(se)

In [61]:
d.sort_values(by="values",ascending=False)

                   product  values
7               whole milk    2513
11        other vegetables    1903
17              rolls/buns    1809
31                    soda    1715
5                   yogurt    1372
..                     ...     ...
164                   bags       4
167        kitchen utensil       4
168  preservation products       2
159              baby food       1
166   sound storage medium       1

[169 rows x 2 columns]

In [62]:
from mlxtend.preprocessing.transactionencoder import TransactionEncoder

In [65]:
tr=TransactionEncoder()
tr.fit(list1)

TransactionEncoder()

In [66]:
dog=pd.DataFrame(tr.transform(list1),columns=tr.columns_)

In [67]:
dog

,Instant food products,UHT-milk,abrasive cleaner,artif. sweetener,baby cosmetics,baby food,bags,baking powder,bathroom cleaner,beef,...,turkey,vinegar,waffles,whipped/sour cream,whisky,white bread,white wine,whole milk,yogurt,zwieback
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9830,False,False,False,False,False,False,False,False,False,True,...,False,False,False,True,False,False,False,True,False,False
9831,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9832,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
9833,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9834,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False

In [68]:

from mlxtend.frequent_patterns import apriori

In [79]:
apriori(dog,min_support=.05,use_colnames=True,max_len=3).sort_values(by="support",ascending=False)

     support                        itemsets
26  0.255516                    (whole milk)
15  0.193493              (other vegetables)
19  0.183935                    (rolls/buns)
23  0.174377                          (soda)
27  0.139502                        (yogurt)
2   0.110524                 (bottled water)
20  0.108998               (root vegetables)
24  0.104931                (tropical fruit)
22  0.098526                 (shopping bags)
21  0.093950                       (sausage)
16  0.088968                        (pastry)
6   0.082766                  (citrus fruit)
1   0.080529                  (bottled beer)
14  0.079817                    (newspapers)
5   0.077682                   (canned beer)
17  0.075648                     (pip fruit)
28  0.074835  (whole milk, other vegetables)
11  0.072293         (fruit/vegetable juice)
25  0.071683            (whipped/sour cream)
3   0.064870                   (brown bread)
9   0.063447                 (domestic eggs)
10  0.058973                   (frankfurter)
12  0.058566                     (margarine)
7   0.058058                        (coffee)
18  0.057651                          (pork)
29  0.056634        (whole milk, rolls/buns)
30  0.056024            (whole milk, yogurt)
4   0.055414                        (butter)
8   0.053279                          (curd)
0   0.052466                          (beef)
13  0.052364                       (napkins)